title: Project
pages: false
files:
  sortable: true
fields:
  title:
    label: Title
    type:  text
  text:
    label: Text
    type:  textarea
  tags:
    label: Tags
    type:  tags
    index: siblings
    help: Separate with with comma.
  materials:
    label: Materials
    type:  tags
    index: siblings
    help: Separate with with comma.
